# Hand-derived risk sets and fractions are recorded in docs/kaplan-meier.md.
# Expected values must not be generated by another survival fit.
kaplan_reference_data <- function() {
  data.frame(
    time = c(1, 2, 2, 3, 5, 6, 1, 2, 3, 3, 4, 6),
    status = c(1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0),
    treatment = factor(rep(c("A", "B"), each = 6), levels = c("A", "B"))
  )
}

expect_kaplan_reference <- function(actual) {
  expect_s3_class(actual$fit, "survfit")
  expect_s3_class(actual$test, "survdiff")
  expect_equal(as.numeric(actual$fit$n), c(6, 6))
  expect_equal(as.numeric(actual$test$n), c(6, 6))
  expect_identical(names(actual$fit$strata), c("treatment=A", "treatment=B"))
  expect_equal(as.numeric(actual$fit$strata), c(5, 5))
  expect_equal(actual$fit$time, c(1, 2, 3, 5, 6, 1, 2, 3, 4, 6))
  expect_equal(actual$fit$n.risk, c(6, 5, 3, 2, 1, 6, 5, 4, 2, 1))
  expect_equal(actual$fit$n.event, c(1, 1, 1, 0, 1, 0, 1, 1, 1, 0))
  expect_equal(actual$fit$n.censor, c(0, 1, 0, 1, 0, 1, 0, 1, 0, 1))
  expect_equal(
    actual$fit$surv,
    c(5 / 6, 2 / 3, 4 / 9, 4 / 9, 0, 1, 4 / 5, 3 / 5, 3 / 10, 3 / 10),
    tolerance = 1e-12
  )

  # O_A = 4, E_A = 47/14, U_A = 9/14, V_A = 2827/1764.
  # The two-group covariance has negative off-diagonal elements.
  expect_equal(as.numeric(actual$test$obs), c(4, 3))
  expect_equal(as.numeric(actual$test$exp), c(47 / 14, 51 / 14),
    tolerance = 1e-12
  )
  expect_equal(
    unname(actual$test$var),
    (2827 / 1764) * matrix(c(1, -1, -1, 1), nrow = 2),
    tolerance = 1e-12
  )
  expect_equal(actual$test$chisq, 729 / 2827, tolerance = 1e-12)
}

test_that("KM steps and log-rank match independent risk-set arithmetic", {
  actual <- pharma_kaplan_meier(
    survival::Surv(time, status) ~ treatment,
    kaplan_reference_data()
  )
  expect_kaplan_reference(actual)
})

test_that("explicit event encodings retain the fixed numerical reference", {
  data <- kaplan_reference_data()
  status <- data$status
  for (encoded in list(status == 1, status + 1)) {
    data$status <- encoded
    actual <- pharma_kaplan_meier(
      survival::Surv(time, status) ~ treatment, data
    )
    expect_kaplan_reference(actual)
  }
})

test_that("selected complete rows retain the independent reference", {
  data <- kaplan_reference_data()
  data$include <- TRUE
  extra <- data[1:6, , drop = FALSE]
  extra$time <- c(0.5, 0.25, 0.1, NA, 2, 1)
  extra$status <- c(1, 0, 1, 1, NA, 1)
  extra$treatment[6] <- NA
  extra$include <- c(FALSE, FALSE, FALSE, TRUE, TRUE, TRUE)
  data <- rbind(data, extra)

  # Exclude three complete decoys, then omit one missing time, status, and group.
  for (action in list(stats::na.omit, stats::na.exclude)) {
    actual <- pharma_kaplan_meier(
      survival::Surv(time, status) ~ treatment, data,
      subset = include, na.action = action
    )
    expect_kaplan_reference(actual)
  }
  expect_error(
    pharma_kaplan_meier(
      survival::Surv(time, status) ~ treatment, data,
      subset = include, na.action = stats::na.fail
    ),
    "missing"
  )
})

test_that("an all-censored curve stays at one without a log-rank test", {
  data <- data.frame(time = c(1, 2, 2, 4), status = rep(FALSE, 4))
  actual <- pharma_kaplan_meier(
    survival::Surv(time, status) ~ 1, data, log_rank = FALSE
  )
  expect_s3_class(actual, "survfit")
  expect_equal(actual$time, c(1, 2, 4))
  expect_equal(actual$n.risk, c(4, 3, 1))
  expect_equal(actual$n.event, c(0, 0, 0))
  expect_equal(actual$n.censor, c(1, 2, 1))
  expect_equal(actual$surv, c(1, 1, 1))
})

test_that("a terminal singleton event has zero log-rank variance contribution", {
  data <- data.frame(
    time = c(1, 2, 3, 1, 2, 2),
    status = c(0, 1, 1, 1, 1, 0),
    treatment = factor(rep(c("A", "B"), each = 3), levels = c("A", "B"))
  )
  actual <- pharma_kaplan_meier(
    survival::Surv(time, status) ~ treatment, data
  )
  expect_equal(as.numeric(actual$fit$n), c(3, 3))
  expect_equal(as.numeric(actual$test$n), c(3, 3))
  expect_equal(actual$fit$time, c(1, 2, 3, 1, 2))
  expect_equal(actual$fit$n.risk, c(3, 2, 1, 3, 2))
  expect_equal(actual$fit$n.event, c(0, 1, 1, 1, 1))
  expect_equal(actual$fit$n.censor, c(1, 0, 0, 0, 1))
  expect_equal(actual$fit$surv, c(1, 1 / 2, 0, 2 / 3, 1 / 3),
    tolerance = 1e-12
  )
  # Event-time (E_A, V_A): (1/2, 1/4), (1, 1/3), (1, 0).
  expect_equal(as.numeric(actual$test$obs), c(2, 2))
  expect_equal(as.numeric(actual$test$exp), c(5 / 2, 3 / 2),
    tolerance = 1e-12
  )
  expect_equal(
    unname(actual$test$var),
    (7 / 12) * matrix(c(1, -1, -1, 1), nrow = 2),
    tolerance = 1e-12
  )
  expect_equal(actual$test$chisq, 3 / 7, tolerance = 1e-12)
})
